# Generated by Django 2.2.14 on 2020-12-14 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boletin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=400)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(upload_to='')),
                ('objetivo', models.IntegerField()),
                ('frecuencia', models.IntegerField()),
                ('fecha_de_creacion', models.DateField()),
            ],
        ),
    ]
