# Generated by Django 2.2.14 on 2020-12-14 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Categorias', '0001_initial'),
        ('Boletines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boletin',
            name='categorias',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Categorias.Categoria'),
        ),
    ]
